//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word2007RedactionTool.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Word2007RedactionTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Word 2007 Redaction Tool ähnelt.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;&lt; &amp;Less ähnelt.
        /// </summary>
        internal static string ButtonLess {
            get {
                return ResourceManager.GetString("ButtonLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;More &gt;&gt; ähnelt.
        /// </summary>
        internal static string ButtonMore {
            get {
                return ResourceManager.GetString("ButtonMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete16 {
            get {
                object obj = ResourceManager.GetObject("Delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find and Mark ähnelt.
        /// </summary>
        internal static string FindAndMarkLabel {
            get {
                return ResourceManager.GetString("FindAndMarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find and mark specific text within the document. ähnelt.
        /// </summary>
        internal static string FindAndMarkSupertip {
            get {
                return ResourceManager.GetString("FindAndMarkSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mark16 {
            get {
                object obj = ResourceManager.GetObject("Mark16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die K ähnelt.
        /// </summary>
        internal static string MarkKeytip {
            get {
                return ResourceManager.GetString("MarkKeytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark ähnelt.
        /// </summary>
        internal static string MarkLabel {
            get {
                return ResourceManager.GetString("MarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark ähnelt.
        /// </summary>
        internal static string MarkScreentip {
            get {
                return ResourceManager.GetString("MarkScreentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click here to access other other options such as redacting all marked regions in the document. ähnelt.
        /// </summary>
        internal static string MarkSplitMenuSupertip {
            get {
                return ResourceManager.GetString("MarkSplitMenuSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark the selected text. When the document is redacted, the text will be replaced. ähnelt.
        /// </summary>
        internal static string MarkSupertip {
            get {
                return ResourceManager.GetString("MarkSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Next16 {
            get {
                object obj = ResourceManager.GetObject("Next16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NR ähnelt.
        /// </summary>
        internal static string NextKeytip {
            get {
                return ResourceManager.GetString("NextKeytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string NextLabel {
            get {
                return ResourceManager.GetString("NextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Mark ähnelt.
        /// </summary>
        internal static string NextScreentip {
            get {
                return ResourceManager.GetString("NextScreentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Navigate to the next redaction mark in the document. ähnelt.
        /// </summary>
        internal static string NextSupertip {
            get {
                return ResourceManager.GetString("NextSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no redaction marks in the current document. ähnelt.
        /// </summary>
        internal static string NoRedactionMarks {
            get {
                return ResourceManager.GetString("NoRedactionMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  occurrence found and marked. ähnelt.
        /// </summary>
        internal static string OccurrenceFound {
            get {
                return ResourceManager.GetString("OccurrenceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  occurrences found and marked. ähnelt.
        /// </summary>
        internal static string OccurrencesFound {
            get {
                return ResourceManager.GetString("OccurrencesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Previous16 {
            get {
                object obj = ResourceManager.GetObject("Previous16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VR ähnelt.
        /// </summary>
        internal static string PreviousKeytip {
            get {
                return ResourceManager.GetString("PreviousKeytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous ähnelt.
        /// </summary>
        internal static string PreviousLabel {
            get {
                return ResourceManager.GetString("PreviousLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous Mark ähnelt.
        /// </summary>
        internal static string PreviousScreentip {
            get {
                return ResourceManager.GetString("PreviousScreentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Navigate to the previous redaction mark in the document. ähnelt.
        /// </summary>
        internal static string PreviousSupertip {
            get {
                return ResourceManager.GetString("PreviousSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redact ähnelt.
        /// </summary>
        internal static string RedactGroupLabel {
            get {
                return ResourceManager.GetString("RedactGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error was encountered while redacting this document. ähnelt.
        /// </summary>
        internal static string RedactionFailed {
            get {
                return ResourceManager.GetString("RedactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redact all marked regions within the current document. ähnelt.
        /// </summary>
        internal static string RedactMenuItemDescription {
            get {
                return ResourceManager.GetString("RedactMenuItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redact Document ähnelt.
        /// </summary>
        internal static string RedactMenuItemLabel {
            get {
                return ResourceManager.GetString("RedactMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redact Document ähnelt.
        /// </summary>
        internal static string RedactScreentip {
            get {
                return ResourceManager.GetString("RedactScreentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redact all marked regions within the current document. The resulting document will be shown in a new window. ähnelt.
        /// </summary>
        internal static string RedactSupertip {
            get {
                return ResourceManager.GetString("RedactSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Review ähnelt.
        /// </summary>
        internal static string ReviewTab {
            get {
                return ResourceManager.GetString("ReviewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to continue searching from the beginning of the document? ähnelt.
        /// </summary>
        internal static string SearchFromBeginning {
            get {
                return ResourceManager.GetString("SearchFromBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to continue searching from the end of the document? ähnelt.
        /// </summary>
        internal static string SearchFromEnd {
            get {
                return ResourceManager.GetString("SearchFromEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified text was not found in the document. ähnelt.
        /// </summary>
        internal static string TextNotFound {
            get {
                return ResourceManager.GetString("TextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove All Marks ähnelt.
        /// </summary>
        internal static string UnmarkAllLabel {
            get {
                return ResourceManager.GetString("UnmarkAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UK ähnelt.
        /// </summary>
        internal static string UnmarkKeytip {
            get {
                return ResourceManager.GetString("UnmarkKeytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unmark ähnelt.
        /// </summary>
        internal static string UnmarkLabel {
            get {
                return ResourceManager.GetString("UnmarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unmark ähnelt.
        /// </summary>
        internal static string UnmarkScreentip {
            get {
                return ResourceManager.GetString("UnmarkScreentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click here to access other options such as removing all redaction marks from the document. ähnelt.
        /// </summary>
        internal static string UnmarkSplitMenuSupertip {
            get {
                return ResourceManager.GetString("UnmarkSplitMenuSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unmark the selected text. ähnelt.
        /// </summary>
        internal static string UnmarkSupertip {
            get {
                return ResourceManager.GetString("UnmarkSupertip", resourceCulture);
            }
        }
    }
}
